apiVersion: v1
kind: Namespace
metadata:
  name: todo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: todo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: todosdb
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {} # ephemeral for Minikube demo; use PVC for persistence
---
apiVersion: v1
kind: Service
metadata:
  name: todo-web
  namespace: todo
spec:
  type: NodePort
  selector:
    app: todo-web
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080 # optional fixed port; remove if you prefer random
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  namespace: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: web
          image: dishagaonkar2002/todo-flask:1.0.2
          imagePullPolicy: Always # pull fresh versions by tag
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo.todo.svc.cluster.local:27017/todosdb
              # simpler also works: mongodb://mongo:27017/todosdb
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
