services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    image: todo-flask:latest
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "5000:5000"

volumes:
  mongo-data:
