services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    image: dishagaonkar2002/todo-flask:1.0.1 # bump tag after changes
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      # optional: FLASK_ENV=development
    ports:
      - "5000:5000"

volumes:
  mongo-data:
